name: Build docker agent image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'agent/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker agent image
      run: docker build . --file /agent/Dockerfile 
